In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

In [19]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-2].values
y = dataset.iloc[:, -1].values

In [20]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [30]:
print(len(X))

50


In [24]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [31]:
# Splitting the dataset into trainset and testset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [32]:
X_test

array([[ 66051.52, 182645.56, 118148.2 ],
       [100671.96,  91790.61, 249744.55],
       [101913.08, 110594.11, 229160.95],
       [ 27892.92,  84710.77, 164470.71],
       [153441.51, 101145.55, 407934.54],
       [ 72107.6 , 127864.55, 353183.81],
       [ 20229.59,  65947.93, 185265.1 ],
       [ 61136.38, 152701.92,  88218.23],
       [ 73994.56, 122782.75, 303319.26],
       [142107.34,  91391.77, 366168.42]])

In [26]:
# Trining the multiple linear regression model on the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [27]:
# predicting the test set results
y_pred = regressor.predict(X_test)
y_pred

array([103901.9 , 132763.06, 133567.9 ,  72911.79, 179627.93, 115166.65,
        67113.58,  98154.81, 114756.12, 169064.01])

In [28]:
# serializing the model regressor using pickle
file='profit_prediction'
pickle.dump(regressor,open(file,'wb'))


In [29]:
saved_model = pickle.load(open(file,'rb'))
saved_model.predict(X_test)

array([103901.9 , 132763.06, 133567.9 ,  72911.79, 179627.93, 115166.65,
        67113.58,  98154.81, 114756.12, 169064.01])